### ISSUE TITLE
wrong sonos controlled by node-sonos-http-api

### ISSUE THREAD

**Issue by tlc** [rgraciano/echo-sonos#10]
I run the test preset which successfully plays my kitchen Sonos.
Then I try "next" and "what's playing" and /next and /state get called.
They don't work and I can tell from the Lambda logs that it's trying to control a different Sonos in my house.
I verify by running /next and /state in my browser and they control a different Sonos.

I've looked at the node-sonos-http-api README (but not the source yet) and it says that actions are usually /{room name}/{action}.  It doesn't say what happens when there is no /{room name}/.
That Sonos may be my master or a random default?

I'm no expert on Alexa, but I think we may need a "slot" for the room name, or hardcoded paths.

**Comment by rgraciano** [comment]
For "what's playing", maybe some integration with /zones would be best, and the lambda service could list everything playing in all zones.

"Next" is trickier - I'm surprised that it would attempt to control a Sonos room that isn't currently playing music.  Is that the behavior you're seeing?

Hardcoding would work, but then you'd have to re-configure the lambda service if you ever changed your presets.  Supporting a room parameter would also work, but then you'd have to remember the room you configured in presets.json as the "coordinator".

Maybe a hybrid approach would be best.  Accept the room as a parameter, and when you say the room as part of the command, it would send "next" right to that room.  If you don't say a room, then call /zones & iterate through the /zones until you find the first zone playing music, & send "next" to the room listed in that zone.

**Comment by tlc** [comment]
BTW, I found a discussion of this very problem in https://github.com/jishi/node-sonos-http-api/issues/94

Note "I'm more confused about that it actually seem to semi-work, since I have never explicitly tried to support these actions without a room reference."

Basically the form you're using doesn't say *what* to act on.

**Comment by rgraciano** [comment]
Yes, I agree that given the API format, /next, /previous, etc shouldn't really work at all.  Those came from another project contributor, so I'm less familiar with them than with the global functions for which the lambda service was originally written.

Parameterizing it will certainly work as an easy short term solution, but hopefully scraping from a global zones request as I suggested above would become the preferred method.

Another way would be to have the lambda service itself keep state, remembering the last player you started music on.  Scraping from a global status would seem to be better, because state could be changed by other clients on your network and ever having the lambda service get thrown out of sync would be annoying.

**Comment by rgraciano** [comment]
Added room control to commands that need it. In the case of /next and /previous, echo-sonos will now find the appropriate coordinator for the room you're asking for, and send the /next or /previous directly to the coordinator. This is to avoid any confusion as to how node-sonos-http-api is supposed to work, and just send to the coordinator always rather than the individual room.

I'll might come back later and add some convenience features that guess at which room you want, in the event you don't specify one. This isn't trivial, though - for example, in my house, the Living Room is hooked up to the TV, so I can't just pick out the first thing with state "PLAYING". It would seem that I'd need to keep the state of the last thing you asked for and then use that as the guess. In my testing, specifying the room is no big deal.

**Comment by tlc** [comment]
Thanks!
